mnemosyne.web/Pages/Users/SignIn.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mnemosyne.data;
using mnemosyne.muse;
using mnemosyne.web.Authentication;
using mnemosyne.web.Utilities;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace mnemosyne.web.Pages.Users
{
    [AllowAnonymous]
    public class SignInModel : PageModel
    {
        private readonly IUserManager _userManager;
        private readonly IUserData _userData;

        [BindProperty]
        public User UserForm { get; set; }

        public SignInModel(IUserManager userManager, IUserData userData)
        {
            _userManager = userManager;
            _userData = userData;
            UserForm = new User();
        }

        public IActionResult OnGet(string returnUrl = "/")
        {
            try
            {
                if (_userManager.IsAuthenticated()) return LocalRedirect(returnUrl);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = "/")
        {
            try
            {
                if (!ModelState.IsValid) return Page();
                if (_userManager.IsAuthenticated()) return LocalRedirect(returnUrl);

                var userRecord = _userData.GetByUsernameAndPassword(UserForm.Username, UserForm.Password);
                if (userRecord == null) return Unauthorized();
                if (userRecord.DeletedBy != null)
                {
                    throw new Exception("User has been deleted.");
                }

                var principal = ClaimsUtility.GetPrinciple(userRecord);
                await _userManager.SignIn(principal);
                TempData["SignedIn"] = true;

                userRecord.LastLogin = DateTime.Now;
                UserForm = _userData.Update(userRecord);
                _userData.Commit();

                return LocalRedirect(returnUrl);
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = ex.Message;
                return Page();
            }
        }

        public async Task<IActionResult> OnPostSignOutAsync(string errorUrl = "/")
        {
            try
            {
                if (_userManager.IsAuthenticated()) await _userManager.SignOut();
                return LocalRedirect("/");
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
                return LocalRedirect(errorUrl);
            }
        }
    }
}

mnemosyne.web/Pages/Shared/_DataTablesScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/DataTables/datatables.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/DataTables/datatables.min.js"></script>
</environment>

mnemosyne.web/Pages/Shared/_DataTablesStylesPartial.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/DataTables/datatables.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css" />
</environment>
<style type="text/css">

    /*re-apply bootstrap5 styles overriden by datatables specificity*/

    table.dataTable.no-footer {
        border-bottom: none;
        border-color: rgb(222, 226, 230);
    }

    table.dataTable tbody tr:last-child,
    table.dataTable tbody tr:last-child th,
    table.dataTable tbody tr:last-child td {
        border-bottom: none;
    }

    table.dataTable tbody tr.alert-warning {
        color: #664d03;
        background-color: #fff3cd;
        border-color: #ffecb5;
    }

    table.dataTable tbody tr.alert-warning .alert-link{
        color: #523e02;
    }

</style>

mnemosyne.web/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mnemosyne.web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-5.0.1-dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-icons-1.5.0/bootstrap-icons.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/rating.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-5.0.1-dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/bootstrap-icons-1.5.0/bootstrap-icons.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/rating.min.css" asp-append-version="true"/>
    </environment>

    @RenderSection("CSS", required: false)
</head>
<body>

    <nav class="fixed-top navbar navbar-expand-md navbar-dark bg-dark">

        <div class="container-md">

            <a class="navbar-brand" asp-page="/Index">B Movie Night</a>

            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup"
                    aria-expanded="false"
                    aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item"><a class="nav-link" asp-page="/Movies/List">Movies</a></li>
                    @if ((await AuthorizationService.AuthorizeAsync(User, "IsAdmin")).Succeeded)
                    {
                        <li class="nav-item"><a class="nav-link" asp-page="/Users/List">Users</a></li>
                    }
                    <li class="nav-item"><a class="nav-link" asp-page="/About">About</a></li>
                    <li class="nav-item"><a class="nav-link" asp-page="/Contact">Contact</a></li>
                </ul>
                @if (!User.Identity.IsAuthenticated)
                {
                    <span class="nav-item">
                        <a class="nav-link text-white ps-0" asp-page="/Users/SignIn">Sign In</a>
                    </span>
                }
                else
                {
                    <span class="nav-item">
                        <a class="nav-link text-white ps-0" asp-page="/Profiles/Details">
                            @User.Identity.Name
                        </a>
                    </span>

                    <!--Really wanting to keep anchor styling-->
                    <form id="sign-out-form" method="post" asp-page="/Users/SignIn" asp-page-handler="SignOut"></form>
                    <span class="nav-item">
                        <a class="nav-link text-white ps-0" asp-page="" onclick="event.preventDefault(); $('#sign-out-form').submit();">Sign Out</a>
                    </span>
                }
            </div>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <!--TODO: navbar padding is not being considered when placing body content -->
    <div class="container-md body-content">

        <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 999">
            <div id="rating-error-toast" class="toast  align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        Oh no! Error rating movie!
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        </div>

        @if (ViewData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                @ViewData["ErrorMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (TempData["SignedIn"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Oh hi <b>@User.Identity.Name</b>!
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (TempData["Message"] != null)
        {
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                @TempData["Message"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - mnemosyne.web</p>
            <p>Placeholder images provided by <a href="https://placeholder.com/">placeholder.com</a>.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-3.6.0/jquery.js"></script>
        <script src="~/lib/bootstrap/bootstrap-5.0.1-dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/rating.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery-3.6.0/jquery.min.js"></script>
        <script src="~/lib/bootstrap/bootstrap-5.0.1-dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/rating.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/lib/moment/moment.js"></script>
    <script type="text/javascript">
        var tooltipTriggerList;
        var toastList;

        $(document).ready(function () {

            $('[data-date]').each((_, el) => {
                let d = $(el).data('date');
                if (d) {
                    let f = $(el).data('date-format') || 'MM/DD/YYYY';
                    let fd = moment(d).format(f);
                    $(el).text(fd);
                }
            });
            
            tooltipTriggerList = $('[data-bs-toggle="tooltip"]').map((_, el) => {
                return new bootstrap.Tooltip(el, { container: 'body', trigger: 'hover' });
            }).get();

            var toastElList = [].slice.call(document.querySelectorAll('.toast'));
            toastList = toastElList.map(function (toastEl) {
                return new bootstrap.Toast(toastEl, { autohide: false });
            }); 

        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

mnemosyne.web/Pages/Shared/_MovieDeleteModal.cshtml
<script type="text/javascript">

    // following changes per modal showing event
    var movieDeleteModal_movieId;
    var movieDeleteModal_movieTitle;

    /**
     * Sets up event handlers for the Movie Delete Modal. Optional DataTables instance can be passed in to remove a row
     * that is id'd by a movie id on successfull delete. (ie. <row id="movie.Id">..) Otherwise, the user will be navigated 
     * back to the movie list page. The parent page is responsible for providing a request verfification token that will be 
     * passed on the delete request header. 
     *
     * Anchors should be setup with the following attributes:
     * data-target="#deleteMovieModal"
     * data-movie-id="movie.Id"
     * data-movie-title="movie.Title"
     */
    function MovieDeleteModalInit(requestVerificationToken, movieTable) {

        var modal = $("#deleteMovieModal");
        modal.on({
            "show.bs.modal": function (event) {

                var button = $(event.relatedTarget);
                movieDeleteModal_movieId = button.data("movie-id");
                movieDeleteModal_movieTitle = button.data("movie-title");

                modal.find(".movie-title").text(movieDeleteModal_movieTitle);

            },
            "hidden.bs.modal": function () {

                var modal = $(this);
                $("#deleteMovieConfirmationButton").removeClass("disabled");
                modal.find(".alert").hide();

            }
        });

        $("#deleteMovieConfirmationButton").on("click", function () {
            $(this).addClass("disabled");
            $.ajax({
                method: "DELETE",
                url: `/api/movies/${movieDeleteModal_movieId}`,
                data: null,
                headers: {
                    RequestVerificationToken: requestVerificationToken,
                },
                success: function () {
                    modal.find(".alert-success").show();
                    if (movieTable) movieTable.row($(`#${movieDeleteModal_movieId}`)).remove().draw();
                },
                error: function () {
                    modal.find(".alert-danger").show();
                }
            });
        });

    }

</script>

<div class="modal fade" id="deleteMovieModal" tabindex="-1" aria-labelledby="deleteMovieModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">                
                <h4 class="modal-title" id="deleteMovieModalLabel">Delete <span class="movie-title"></span></h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success" style="display: none">
                    <b><span class="movie-title"></span></b> successfully deleted!
                </div>
                <div class="alert alert-danger" style="display: none">
                    Error deleting <b><span class="movie-title"></span></b>. Please refresh the page and try again.
                </div>
                Are you sure you want to delete <b><span class="movie-title"></span></b>?
            </div>
            <div class="modal-footer">
                <a id="deleteMovieConfirmationButton" class="btn btn-danger">Yes!</a>
                <a class="btn btn-secondary" data-bs-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

mnemosyne.web/Pages/Shared/_MovieLookUp.cshtml
<script type="text/javascript">

    /**
     * Automatically setups up a page to look up movies against omdb. Script will look for html elements with specific attributes
     * and work against those. Only attributes requied are movie-title and movie-lookup. movie-lookup wires up the button that 
     * triggers the api call. movie-title is needed to perform the search. Any data returned from the api call will be used to 
     * override any input with the associated attributes. Duplicate attributes can exist. 
     * 
     * movie-look - button to trigger api call
     * movie-title - input to search for
     * 
     * movie-year - year movie was released, overriden by api call
     * movie-director - director(s) of movie, overriden by api call
     * movie-genre - genre of movie, overriden by api call, if multiple genres are found in omdb this is the first genre that maps to our enum
     * movie-poster - movie poster, overriden by api call, can be applied on both an input or img tag
     * */
    $(document).ready(function () {

        let lookUpButton = $('button[movie-lookup]');

        let titleInput = $('input[movie-title][type="text"]');
        let yearInput = $('input[movie-year][type="number"]');
        let directorInput = $('input[movie-director][type="text"]');
        let genreInput = $('select[movie-genre]');

        let posterInput = $('input[movie-poster][type="text"], input[movie-poster][type="hidden"]');
        let posterImg = $('img[movie-poster]');

        lookUpButton.click(_ => {

            $('fieldset').prop('disabled', true);
            $('fieldset').find('[data-bs-toggle="tooltip"]').tooltip('hide');

            let title = titleInput.val();

            $.ajax({
                method: "GET",
                url: `/api/lookup/findmovie/?title=${title}`,
                success: (data) => {
                    if (!data.title) {
                        alertMovieLookUp(`Unable to find movie <strong>${title}</strong>`, 'warning');
                        return;
                    }

                    $('#lookup-alert-container .alert .btn-close').click();

                    titleInput.val(data.title);
                    yearInput.val(data.year);
                    directorInput.val(data.director);
                    genreInput.val(data.genre);

                    if (data.poster) {
                        posterInput.val(data.poster);
                        posterImg.attr('src', data.poster);
                    }
                },
                error: function () {
                    alertMovieLookUp('Error looking up movie title.', 'danger');
                },
                complete: function () {
                    $('fieldset').prop('disabled', false);
                }
            });

        });
    });

    function alertMovieLookUp(message, type) {
        $('div[lookup-alert-container]').html([
            `<div class="alert alert-${type} alert-dismissible" role="alert">`,
            `   <div>${message}</div>`,
            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
            '</div>'
        ].join(''));
    }

</script>

mnemosyne.web/Pages/Shared/_RatingAverage.cshtml
@model double

<div class="rating-average-container">
    <div class="rating-average-fill" style="--rating: @(Model);"></div>
</div>

mnemosyne.web/Pages/Shared/_RatingInput.cshtml
@model mnemosyne.muse.Rating
@using mnemosyne.muse 

@{
    var name = ViewData["name"] ?? "rating";
}

@functions {
    public bool isChecked(int v)
    {
        return (Model?.Value ?? 0) == v;
    }
}

<div class="d-inline-block">
    <div id="@(name)" class="rating-radio" data-movie-id="@(Model?.MovieId ?? 0)">
        <input class="d-none" type="radio" id="@(name)_0" asp-for="Value" value="0" checked=@isChecked(0)/>
        <label class="d-none" for="@(name)_0"></label>

        @for (int i = 1; i <= Rating.Max; i++)
        {
            <input type="radio" id="@(name)_@(i)" asp-for="Value" value="@i" checked=@isChecked(i) />
            <label for="@(name)_@(i)"></label>
        }
    </div>
</div>